### ISSUE TITLE
chore: Text area missing proper styles

### ISSUE THREAD

**Issue by arselt** [arselt/cra-xstate-transfer-machine#1]
![image](https://user-images.githubusercontent.com/56246139/211691912-657650ec-504a-460d-9f3c-aba72b3efc24.png)

- [ ] fix paddings in textarea
- [ ]  change font-family

**Comment by harshitsahush** [comment]
Hi!
I'll be more than happy to fix the issue. However, this is gonna be my first contribution. Could you please guide me step-by-step.

**Comment by BoltUltra** [comment]
Can I work on this?

**Comment by arselt** [comment]
Thank you for the interest! 
First time labeling an issue on a public repo of mine 🤣 didn't expect this to be solved by someone else.

But... Thank you!
